server:
  port: 7004

spring:
  application:
    name: ec-order-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 47.101.187.117:8848

  #rabbitMQ 消息队列配置
  rabbitmq:
    host: 47.101.187.117
    port: 5672
    virtual-host: /
    username: admin
    password: 2018LYW@#$
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.187.117:3306/ec_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2018LYW@#$

  #redis 配置
  redis:
    host: 47.101.187.117
    port: 6379
    password: 2018LYW@#$


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO


#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  order_close_delay_queue: order.close.delay.queue
  #延迟队列的消息过期后转发的队列
  order_close_queue: order.close.queue
  #交换机
  order_event_exchange: order.event.exchange
  #进入延迟队列的路由key
  order_close_delay_routing_key: order.close.delay.routing.key
  #消息过期，进入释放队列的key,进入死信队列的key
  order_close_routing_key: order.close.routing.key
  #消息过期时间,毫秒,测试改为15秒
  ttl: 300000


#支付宝配置
alipay:
  #支付成功后的跳转页面
  success_return_url: https://xdclass.net
  #支付宝通知回调接口
  callback_url: https://7vtdb86pmr74.ngrok2.xiaomiqiu.cn/order-server/api/callback/order/v1/alipay


